### ISSUE TITLE
File size issue

### ISSUE THREAD

**Issue by caspahouzer** [Astrovic/TiDropboxAPIv2#1]
Hello,

first of all: great module. Exactly for what I've been searching for.

I've just have one issue. Using my upload code works on simulator great. the files have the exact size. Starting the app on the device, my uploaded zip file has 0 bytes and an uploaded textfile has the following content

`{"path":"/hash.txt","mode":"overwrite","autorename":false,"mute":true}`

Do you know what I'm doing wrong? I read the files from my cache directory and I'm working only on iOS

These are the files from the simulator: https://cl.ly/2a1C023C2q2G
Here from device: https://cl.ly/0Q1q142B1l0N

**Comment by Astrovic** [comment]
Hello,
I'm glad that the module is useful.

Have you tried a `Ti.API.debug(f.exists())` to see if you are reading the file correctly? I think that's the problem.

**Comment by caspahouzer** [comment]
Solved. I deleted it after executing a function before... _dumb_
