### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by caspahouzer** [Astrovic/TiDropboxAPIv2#2]
Ok, I'm here again an stuck.

When I download a file... where the hell is this file? It's not in the response of the API (https://www.dropbox.com/developers/documentation/http/documentation#files-download)

**Comment by Astrovic** [comment]
In onSuccessCallback, you must use xhr.responseData instead of xhr.responseText. And of course, you decide where and how to save the file ;)
For example, in the case of a text file, one possible use would be as follows :

``` js
function onSuccessCallback(xhr) {
  $.activityBgView.hide();
  Ti.API.debug("onSuccessCallback checkins response-> " + xhr.responseText);

  // Write downloaded data in a file
  if(xhr.responseData){
    var filePath = Titanium.Filesystem.applicationDataDirectory + "myDownloadedFile.txt";
    var file = Titanium.Filesystem.getFile(filePath);
        file.write(xhr.responseData);

    // I check if I saved the file properly
    setTimeout(function(){
      Ti.API.debug(filePath + " exists? ---> " + file.exists());
      if(file.exists()){
        if(OS_IOS){
          Ti.UI.iOS.createDocumentViewer({url:filePath}).show();
        };
      }else{
        alert("Something went wrong in the file writing...");
      };
    },1000);
  };
};
```

**Comment by caspahouzer** [comment]
Responsedata... Yeah. Thank you
- Sebastian 

Sent from my iPhone

**Comment by caspahouzer** [comment]
Works great. I changed the UI a little, as you see here: https://cl.ly/36080I2f2t2r

**Comment by Astrovic** [comment]
Great, I'm glad ;)
