### ISSUE TITLE
I am getting issue but previous works fine for me. Please any one can help me, find image that contains issue details.

### ISSUE THREAD

**Issue by anilundala1** [Astrovic/TiDropboxAPIv2#5]
![screen shot 2018-09-20 at 3 49 31 pm](https://user-images.githubusercontent.com/43437400/45813331-fc3f1b80-bcef-11e8-8662-949a418415b3.png)

**Comment by Astrovic** [comment]
It looks like you're running too many requests. Dropbox has limits in the use of the API, so we must optimize their use

**Comment by anilundala1** [comment]
But i created new account and i access with new app-key and redirect uri but still same issue coming. I am logged in with only one account. Whenever login button clicked on that time doesn't logged in that's why i click login more times.

**Comment by anilundala1** [comment]
i need to change only this line TiDropbox.init('cyvn9z6hi1axnfs', 'https://DropboxOAuth2Flow.yug'); with app-key and redirect uri. Is anything else i need to change.

generateAuthUrl checkins response-> {"access_token":"Sr4ZWCay-CAAAAAAAAAAsOk7rHKwpVgjHaQr0H-07KnWv76BHYo-bl4tlxGlYo23","success":true,"msg":"Ok, you have an access token"} **like this not generating**.

**Comment by Astrovic** [comment]
But are you using Google button for login, or Dropbox mail and password? The message "Too many requests" when appears?

**Comment by anilundala1** [comment]
Both ways i am unable to login.

I was try to login 2 ways.
1. Login with Dropbox mail and password not able to login. Then on that time if i click on google button for login then "Too many requests" issue coming.
2. When i click on   Google button for login after adding credentials that doesn't move to next screen. Still there in login page only.

**Comment by Astrovic** [comment]
Then there must be some problem with your configuration. In the settings of the Dropbox app, have you correctly configured the Redirect URIs of the OAuth 2? Have you allowed the implicit grant?

**Comment by anilundala1** [comment]
Yes i configured correct uri only.But i didn't add Webhook URIs remaining all the things i configured correctly.

**Comment by Astrovic** [comment]
It's not necessary. Are you using https://dropboxoauth2flow.yug? Because it doesn't seem to work.

**Comment by Astrovic** [comment]
You should use a valid https uri, otherwise use https://www.dropbox.com/

**Comment by anilundala1** [comment]
Can you please suggest one URI. Because when i add uri i didn't get any issue.

**Comment by Astrovic** [comment]
I've already suggested it above

**Comment by anilundala1** [comment]
Yes i resolved the issue. Thanks Astrovic for your support.
